### ISSUE TITLE
Typo and error in round whitefish data

### ISSUE THREAD

**Issue by PeterMous** [droglenc/FSAdata#3]
I found errors in the following datasets (or, rather, in the accompanying documentation): 
RWhitefishAI 	Ages and lengths of Round Whitefish.
RWhitefishIR 	Ages and lengths of Round Whitefish.

- Typo in the scientific name: Prosopium cylindraecum -> cylindraceum
- TL is in inch, not cm

**Comment by droglenc** [comment]
Fixed in latest version on GitHub.  Thanks.
